In [1]:
import pandas as pd

df = pd.read_csv('/root/autodl-tmp/yankai/data/data/simplified_trn_536066val_tst_with_weekend.csv', sep='\t')

In [2]:
df

,weekday,f_1,f_2,f_3,f_4,f_5,f_6,f_8,f_9,f_10,...,f_72,f_73,f_74,f_75,f_76,f_77,f_78,f_79,is_clicked,is_installed
0,6,50,20095,563,31686,15908,590,21218,21533,22970,...,0.000000,0.000000,0.077128,1.156922,0.269948,0.0,0.000000,0.000000,0,0
1,2,46,14963,22294,26466,25604,12305,21218,9638,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
2,7,51,17758,22294,4870,25604,11727,21218,31372,22970,...,1.142243,0.000000,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3,1,59,5156,22294,18971,25604,22787,19203,6675,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
4,6,50,11077,7152,18575,25604,32377,18800,21533,19343,...,0.000000,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646820,2,67,26325,22294,4896,25604,23841,21218,14659,22970,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646821,2,67,14963,22294,26466,21545,8488,19203,14659,22970,...,0.571121,0.571121,0.115692,1.156922,0.269948,0.0,37.384575,37.384575,0,0
3646822,2,67,20095,563,31686,21545,590,21218,14659,22970,...,2.284486,1.142243,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3646823,2,67,890,7152,497,21545,876,19606,14659,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646824,2,67,27426,7152,3786,21545,29871,18800,14659,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0

In [3]:
df[-160973:]

,weekday,f_1,f_2,f_3,f_4,f_5,f_6,f_8,f_9,f_10,...,f_72,f_73,f_74,f_75,f_76,f_77,f_78,f_79,is_clicked,is_installed
3485852,2,67,26325,7152,21563,19475,31440,21621,14659,21574,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0,0
3485853,2,67,20095,563,22861,19475,21280,19203,14659,21574,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3485854,2,67,890,22294,18294,21545,20210,18800,9638,19343,...,0.000000,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3485855,2,67,20095,563,22861,25604,21280,18800,14659,22970,...,2.284486,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3485856,2,67,27426,22294,11338,19475,23855,21218,9638,21574,...,0.000000,0.000000,0.077128,0.077128,0.077128,0.0,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646820,2,67,26325,22294,4896,25604,23841,21218,14659,22970,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646821,2,67,14963,22294,26466,21545,8488,19203,14659,22970,...,0.571121,0.571121,0.115692,1.156922,0.269948,0.0,37.384575,37.384575,0,0
3646822,2,67,20095,563,31686,21545,590,21218,14659,22970,...,2.284486,1.142243,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3646823,2,67,890,7152,497,21545,876,19606,14659,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646824,2,67,27426,7152,3786,21545,29871,18800,14659,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0

In [5]:
df[-160973-177299:-160973]['f_1'].unique()

array([60, 53, 66])

In [6]:
ori_df = pd.read_csv('/root/autodl-tmp/xingmei/RecSys23/data/simplified_trn_val_tst_with_weekday.csv', sep='\t')

In [16]:
trn_df = ori_df[0:3387880]
val_df = ori_df[3387880:-160973]
tst_df = ori_df[-160973:]

In [17]:
trn_else = trn_df[(trn_df['f_1'] != 60) & (trn_df['f_1'] != 53)]

In [18]:
trn_df_60 = ori_df[ori_df['f_1'] == 60]
trn_df_53 = ori_df[ori_df['f_1'] == 53]
split_row = int(trn_df_60.shape[0] * 0.5)
trn_df_60_1 = trn_df_60[0:split_row]
trn_df_60_2 = trn_df_60[split_row:]
split_row = int(trn_df_53.shape[0] * 0.5)
trn_df_53_1 = trn_df_53[0:split_row]
trn_df_53_2 = trn_df_53[split_row:]
split_row = int(val_df.shape[0] * 0.5)
val_df_1 = val_df[0:split_row]
val_df_2 = val_df[split_row:]

In [19]:
trn_df = pd.concat([trn_else, trn_df_60_1, trn_df_53_1, val_df_1], axis=0)
val_df = pd.concat([trn_df_60_2, trn_df_53_2, val_df_2], axis=0)
all_df = pd.concat([trn_df, val_df, tst_df], axis=0)

In [20]:
all_df

,weekday,f_1,f_2,f_3,f_4,f_5,f_6,f_8,f_9,f_10,...,f_72,f_73,f_74,f_75,f_76,f_77,f_78,f_79,is_clicked,is_installed
0,6,50,20095,563,31686,15908,590,21218,21533,22970,...,0.000000,0.000000,0.077128,1.156922,0.269948,0.0,0.000000,0.000000,0,0
2,2,46,14963,22294,26466,25604,12305,21218,9638,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3,7,51,17758,22294,4870,25604,11727,21218,31372,22970,...,1.142243,0.000000,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
4,1,59,5156,22294,18971,25604,22787,19203,6675,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
5,6,50,11077,7152,18575,25604,32377,18800,21533,19343,...,0.000000,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646820,2,67,26325,22294,4896,25604,23841,21218,14659,22970,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646821,2,67,14963,22294,26466,21545,8488,19203,14659,22970,...,0.571121,0.571121,0.115692,1.156922,0.269948,0.0,37.384575,37.384575,0,0
3646822,2,67,20095,563,31686,21545,590,21218,14659,22970,...,2.284486,1.142243,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3646823,2,67,890,7152,497,21545,876,19606,14659,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646824,2,67,27426,7152,3786,21545,29871,18800,14659,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0

In [24]:
df

,weekday,f_1,f_2,f_3,f_4,f_5,f_6,f_8,f_9,f_10,...,f_72,f_73,f_74,f_75,f_76,f_77,f_78,f_79,is_clicked,is_installed
0,6,50,20095,563,31686,15908,590,21218,21533,22970,...,0.000000,0.000000,0.077128,1.156922,0.269948,0.0,0.000000,0.000000,0,0
1,2,46,14963,22294,26466,25604,12305,21218,9638,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
2,7,51,17758,22294,4870,25604,11727,21218,31372,22970,...,1.142243,0.000000,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3,1,59,5156,22294,18971,25604,22787,19203,6675,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
4,6,50,11077,7152,18575,25604,32377,18800,21533,19343,...,0.000000,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3646820,2,67,26325,22294,4896,25604,23841,21218,14659,22970,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646821,2,67,14963,22294,26466,21545,8488,19203,14659,22970,...,0.571121,0.571121,0.115692,1.156922,0.269948,0.0,37.384575,37.384575,0,0
3646822,2,67,20095,563,31686,21545,590,21218,14659,22970,...,2.284486,1.142243,0.115692,1.156922,0.269948,0.0,37.384575,0.000000,0,0
3646823,2,67,890,7152,497,21545,876,19606,14659,19343,...,0.571121,0.000000,0.000000,1.156922,0.269948,0.0,0.000000,0.000000,0,0
3646824,2,67,27426,7152,3786,21545,29871,18800,14659,19343,...,0.000000,0.000000,0.115692,1.156922,0.269948,0.0,0.000000,0.000000,0,0

In [27]:
all_df_ = all_df.reset_index(inplace=False, drop=True)

In [34]:
a=((all_df_ == df).all())

In [35]:
a[a==False]

f_30    False
f_31    False
f_43    False
f_51    False
f_58    False
f_59    False
f_64    False
f_65    False
f_66    False
f_67    False
f_68    False
f_69    False
f_70    False
dtype: bool

In [38]:
pd.DataFrame({'index':all_df.index.to_list()}).to_csv('/root/autodl-tmp/xingmei/RecSys23/data/index_val536066.csv', sep='\t', index=False)